import Head from 'next/head'
import Image from 'next/image'
import { trpc } from '@/utils/trpc'
import { getOptionForVote } from '@/utils/getRandomPokemon'

export default function Home() {

  const [firstId, secondId] = getOptionForVote();

  return (
    <>
      <Head>
        <title>Round Mon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen w-screen flex flex-col justify-center items-center'>
        <div className='text-2xl text-center'>Which Pokemon is Rounder?</div>

        <div className='mt-10 border-2 p-8 flex justify-between items-center'>
          <div className='bg-purple-300 w-20 h-20 text-black'>{firstId}</div>
          <div className='px-8'>VS</div>
          <div className='bg-purple-300 w-20 h-20 text-black'>{secondId}</div>
        </div>
      </main>
    </>
  )
}
